baseURL = "https://k-cross.github.io"
languageCode = "en-us"
title = "k-cross"
theme = "sam"
enableRobotsTXT = true # generate robots.txt
pygmentsCodefences = true # Syntax highlighting

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Abstractions from madness!"

# Metadata
    description         = "Abstractions from madness!"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about"
    text = "who?"

[[params.mainMenu]]
    link = "/posts"
    text = "what?"

[[params.mainMenu]]
    link = "/purpose"
    text = "why?"

[blackfriday]
  hrefTargetBlank = true
