baseURL = "https://k-cross.github.io"
languageCode = "en-us"
title = "k-cross"
theme = "sam"
preserveTaxonomyNames = true
enableRobotsTXT = true # generate robots.txt
pygmentsCodefences = true # Syntax highlighting
#Paginate = 5

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Call me Sam, a theme for Hugo."

# Metadata
    description         = "A new Hugo site."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/posts"
    text = "writing"

[[params.mainMenu]]
    link = "/gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "/about"
    text = "who is sam?"
    
[params.info]
  description = "Abstractions from madness!"
  title404 = "Nothing's here!"

[params.comments]
  enable = false

[taxonomies]
  author = "authors"
  category = "categories"
  series = "series"
  tag = "tags"

[blackfriday]
  hrefTargetBlank = true
